language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make build
branches:
  only:
  - master
  deploy:
  provider: s3
  access_key_id: "AKIAISDYOXCU7YH4J4FQ"
  secret_access_key: "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"
  bucket: "S3 Bucket"
