language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make build
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAISDYOXCU7YH4J4FQ
  secret_access_key:
    secure: DLpYIJ//brpgdLMvBnxwog1z3HKQxKiiiB/8EbSwRZnnz8xfImRvAAERcGfLllbMl+oJU2IWHVhzLWjU5f4iOzMzxvN4qb2uOJWmobxAICqt6ptWGAqF+vT5gYiclrnKuy5siOLPhIG6a6SXZTY3vRuLvZ9e2ReUMdmiEmgpMgU38CtrbCr7eATFj3J/jSGBDM4fMgjMJpHOCVTi/TTu0VsUqVmTTA73BT0cZnp7+M4njutY9O9/lj3Cp4Mv0AVzfesx9UK1V6qpBxoDx0PiBUB0wXxKGtaBYoaoHom0Opm88W2XgRbCXqBueGI9wWQ0czEJwCKJ6yWz+VEGRgQ1YGssvjPCtC5/RPifiZJKk5Gyeqj6NgJu+LTOFwSqiQMwUbtijms7+hLeAwvU495+IzL//b7RmjmK6wlZJerdyflkslMWa6iUXbU4ynDi6QWj0gvoLF+0gzA/x+JoePcn+Bqod6wBHHiG4h4pkpqm3UzxNM8DT/RWluM8mH5pPfMeoUg9tyLlP9UJQDTdJydEnFgnHGnuliI5JxVKSQ6biCEB2qIdL+c+ZQuqAk5ec2ExkY6U1K5LPuV5tGQalQW2X4ZhcqKWX2qzUdXRNHxyr9Z+86Po4krLfPqGkS5LRF9uXJxXddMeEgXgIIm5/NBjiTZOIUTVaTk1QktMJNQ9EZs=
  bucket: "S3 Bucket"
