baseurl = "http://benmook.co.s3-website-us-east-1.amazonaws.com"
title = "Ben Mook"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]


[params]
  description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
  logo = "fa-newspaper-o"
  copyright = "2018"
  favicon = "static/images/mook_favicon.png"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/BenMook"


[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"


[languages]
[languages.en]
languageName = "English"
weight = 1

title = "Ben Mook"
description = '<!--[-->Content strategist with a background in UX design and a foundation in journalism<!--]-->'
